### ISSUE TITLE
v3 attempt to get length of a nil value

### ISSUE THREAD

**Issue by JMarkin** [lukas-reineke/indent-blankline.nvim#614]
Hello,
If enabled rainbow-delimiters.nvim and opened docker-compose.yml I get error

> Error detected while processing BufReadPost Autocommands for "*":
Error executing lua callback: /usr/local/share/nvim/runtime/filetype.lua:30: Error executing lua: /usr/local/share/nvim/runtime/filetype.lua:31: BufReadPost Autocommands for "*"..FileType Autocommands for "*": Vim(append):Error e
xecuting lua callback: .../share/nvim/lazy/indent-blankline.nvim/lua/ibl/hooks.lua:193: attempt to get length of a nil value
stack traceback:
        .../share/nvim/lazy/indent-blankline.nvim/lua/ibl/hooks.lua:193: in function 'fn'
        ...l/share/nvim/lazy/indent-blankline.nvim/lua/ibl/init.lua:327: in function 'refresh'
        ...are/nvim/lazy/indent-blankline.nvim/lua/ibl/autocmds.lua:17: in function <...are/nvim/lazy/indent-blankline.nvim/lua/ibl/autocmds.lua:16>
        [C]: in function 'nvim_cmd'
        /usr/local/share/nvim/runtime/filetype.lua:31: in function </usr/local/share/nvim/runtime/filetype.lua:30>
        [C]: in function 'nvim_buf_call'
        /usr/local/share/nvim/runtime/filetype.lua:30: in function </usr/local/share/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_cmd'
        /usr/local/share/nvim/runtime/filetype.lua:31: in function </usr/local/share/nvim/runtime/filetype.lua:30>
        [C]: in function 'nvim_buf_call'
        /usr/local/share/nvim/runtime/filetype.lua:30: in function </usr/local/share/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_buf_call'
        /usr/local/share/nvim/runtime/filetype.lua:30: in function </usr/local/share/nvim/runtime/filetype.lua:10>
Error detected while processing BufWinEnter Autocommands for "*":
Error executing lua callback: .../share/nvim/lazy/indent-blankline.nvim/lua/ibl/hooks.lua:193: attempt to get length of a nil value
stack traceback:
        .../share/nvim/lazy/indent-blankline.nvim/lua/ibl/hooks.lua:193: in function 'fn'
        ...l/share/nvim/lazy/indent-blankline.nvim/lua/ibl/init.lua:327: in function 'refresh'
        ...are/nvim/lazy/indent-blankline.nvim/lua/ibl/autocmds.lua:17: in function <...are/nvim/lazy/indent-blankline.nvim/lua/ibl/autocmds.lua:16>

Example file 
```yaml
version: "3"

services:
  locust:
    image: locustio/locust
    command: -f /mnt/locustfile.py --master
    volumes:
      - .:/mnt
    ports:
      - 8089:8089

  worker-locust:
    image: locustio/locust
    volumes:
      - .:/mnt
    command: -f /mnt/locustfile.py --worker --master-host locust
```
